### ISSUE TITLE
QuickStart not deploying in us-east-1 due to versioning issue.

### ISSUE THREAD

**Issue by nishantcasey** [aws-quickstart/quickstart-atlassian-jira#16]
A customer of mine is attempting to deploy the solution in us-east-1 but this is not functioning.
After some testing I have been able to find that the problem seems to be down to the instance level setup.

Effectively, when the init script for atlassian runs: 

/etc/init.d/atl-init-jira

This script attempts to fetch a binary from http://s3.amazonaws.com/atlassian-software/releases/servicedesk/atlassian-servicedesk-3.6.2x64.bin

However - if I attempt to access this from a browser or directly from curl - the endpoint is AccessDenied.

Changing this to http://s3.amazonaws.com/atlassian-software/releases/servicedesk/atlassian-servicedesk-3.5.0x64.bin manually in the init script allows the service to start - however, it still does not deploy successfully. 

Can you please take a look/open up the permissions for 3.6.2 or alter the init script so that customers do not face this issue.

**Comment by dikeert** [comment]
Both URLs you've provided are not valid URLs for JIRA Core/Software and Service Desk installers. The valid url is: `https://s3.amazonaws.com/atlassian-software/releases/servicedesk/atlassian-servicedesk-3.2.3-x64.bin`.

Let me double check if template does the right thing.

**Comment by dikeert** [comment]
I can confirm that latest version of JIRA's installation scripts has proper installer URL:

```
local JIRA_INSTALLER="atlassian-${ATL_JIRA_NAME}-${JIRA_VERSION}-x64.bin"
```

You can see it it [here](https://bitbucket.org/atlassian/atlassian-aws-deployment/src/a3faf15192c95de0e4038e6837a45d0b2c68cd26/ami/scripts/init.d/atl-init-jira.sh?at=master&fileviewer=file-view-default#atl-init-jira.sh-226)

So the questions rises - was there any modifications to JIRA's installation scripts?

I must note that it is perfectly valid, expected and intended use of those scripts to adjust them to the needs of particular customer.

**Comment by jumateg** [comment]
I've checked and the instance scripts are set the same way. Nothing in the template modifies the scripts either. I think nishantcasey just missed a few dashes from the links somehow. The problem is the JIRA_VERSION is being retrieved as 3.6.2, however the .bin for that version does not seem to be available/public in the bucket.

The scripts are getting the version from here:

2017-08-18 09:52:09 [prepareInstaller]:  Checking if installer has been downloaded already
2017-08-18 09:52:09 [downloadInstaller]:  Downloading installer description from https://s3.amazonaws.com/atlassian-software/releases/servicedesk/latest

This returns 3.6.2:
curl  https://s3.amazonaws.com/atlassian-software/releases/servicedesk/latest
3.6.2

Which cannot be downloaded:
wget  https://s3.amazonaws.com/atlassian-software/releases/servicedesk/atlassian-servicedesk-3.6.2-x64.bin
...
HTTP request sent, awaiting response... 403 Forbidden
2017-08-18 13:43:09 ERROR 403: Forbidden.

For an older version (like 3.2.3) the file is available still, so this URL would work:
https://s3.amazonaws.com/atlassian-software/releases/servicedesk/atlassian-servicedesk-3.2.3-x64.bin

I think that there has been a new release, and although its listed as the latest now, the actual .bin are not public in that bucket or not in the same path than older versions.

**Comment by dikeert** [comment]
Yep, can confirm that it says 'Forbidden' for 3.6.2. Let me fix it quickly...

**Comment by dikeert** [comment]
Ok, done, should be accessible now.
