### ISSUE TITLE
Update ELB to ELBv2 ALB

### ISSUE THREAD

**Issue by tlindsay42** [aws-quickstart/quickstart-atlassian-jira#26]
The load balancer in the templates are now considered previous generation and should be updated to the Application Load Balancer.

**Comment by seb-steuer** [comment]
It's worth noting that ALB only supports stickiness using its own cookie, the old ELB supports user defined application generated cookie where the CloudFormation template actually uses that feature by defining JSESSIONID to be the cookie to look for

That being said I believe it would still work with ALB no problem

**Comment by tlindsay42** [comment]
Yep, it does.

**Comment by seb-steuer** [comment]
@tlindsay42 
Hi, I think atlassian do not care about that repo at all. But that is the one that aws marketplace offering points to.
I think you will find interesting progress here:
https://bitbucket.org/atlassian/atlassian-aws-deployment

Although not using ALB I'm sure if you post there you'll be more likely to get a response.
That finding for me is especially frustrating because i implemented vast majority of features myself and it turns out it was there on bitbucket

**Comment by tlindsay42** [comment]
@seb-steuer 
Thanks!  I assumed as much a while back by their lack of response, and I didn't like a few aspects of their design, so I built my own template in Terraform based on theirs.  I wish that I could share it.

**Comment by tonynv** [comment]
cleaning old-issues
